version: '3'

services:
  myapp-mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_USER=sparksjoy
      - MYSQL_PASSWORD=sparksjoy 
      - MYSQL_ROOT_PASSWORD=sparksjoy 
      - MYSQL_DATABASE=sparksjoy 
    ports:
      - 3306:3306

  myapp-main:
    image: nectiasoftware2000/quarkus-poc:v2
    restart: on-failure
    depends_on: 
      - myapp-mariadb
    ports:
      - 8080:8080
